{% set name = "tiktoken" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiktoken-{{ version }}.tar.gz
  sha256: ace62a4ede83c75b0374a2ddfa4b76903cf483e9cb06247f566be3bf14e6beed

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - wheel
    - setuptools-rust {{ setuptools_rust }}
    - pip
  run:
    - python {{ python }}
    - regex >=2022.1.18
    - requests {{requests}}

test:
  imports:
    - tiktoken
    - tiktoken_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openai/tiktoken
  summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
